public class Stats
{
	public string kicks;
	public string handballs;
	public string disposals;
	public string marks;
	public string goals;
	public string behinds;
	public string tackles;
	public string hitouts;
	public string frees_for;
	public string frees_against;
	public string contested_posessions;
	public string uncontested_posessions;
	public string effective_disposals;
	public string effective_disposals_percentage;
	public string clangers;
	public string contested_marks;
	public string goal_assists;
	public string inside_50s;
	public string marks_inside_50;
	public string clearances;
	public string rebound_50s;
	public string one_percenters;
	public string bounces;
	public string time_on_ground;
	public string supercoach;
	public string afl_fantasy;
}
